name: Java CI with Maven

on:
  push:
    branches: [ "graylog" ]
  pull_request:
    branches: [ "graylog" ]

# Cancel running build when a new ref gets pushed.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      env:
        MAVEN_OPTS: >
          -DtrimStackTrace=false
          -Djansi.force=true
        MAVEN_ARGS: >
          --batch-mode --fail-fast --no-transfer-progress --show-version
      run: mvn verify -Pits --file pom.xml
